name = "errordiffusion-cc"
main = "src/index.js"
compatibility_date = "2026-05-12"
account_id = "98b823762cb6be14fb4fb00c935fadf1"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
